# Generated by Django 6.0.8 on 2026-10-02 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='اسم الحي')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'حي',
                'verbose_name_plural': 'الأحياء',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WaterSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'السبت'), (1, 'الأحد'), (2, 'الاثنين'), (3, 'الثلاثاء'), (4, 'الأربعاء'), (5, 'الخميس'), (6, 'الجمعة')], db_index=True, verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='من')),
                ('end_time', models.TimeField(verbose_name='إلى')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة')),
                ('source', models.CharField(choices=[('manual', 'إدخال يدوي'), ('gaza-city.org', 'gaza-city.org')], default='manual', max_length=30, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_slots', to='locations.location', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'موعد مياه',
                'verbose_name_plural': 'جدول المياه',
                'ordering': ['day', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('day__gte', 0), ('day__lte', 6)), name='waterslot_day_range'), models.CheckConstraint(condition=models.Q(('start_time', models.F('end_time')), _negated=True), name='waterslot_start_ne_end')],
            },
        ),
    ]
