# Generated by Django 6.0.8 on 2026-10-05 13:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_remove_waterslot_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(0, 'السبت'), (1, 'الأحد'), (2, 'الاثنين'), (3, 'الثلاثاء'), (4, 'الأربعاء'), (5, 'الخميس'), (6, 'الجمعة')]), verbose_name='الأيام')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'موعد توزيع',
                'verbose_name_plural': 'جدول توزيع المياه',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DistributionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='العنوان')),
                ('sort_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='water.distributiongroup', verbose_name='الموعد')),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'العناوين',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
