# Generated by Django 6.0.8 on 2026-09-30 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='اسم المستخدم')),
                ('action', models.CharField(choices=[('CREATE', 'إضافة'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('RESTORE', 'استعادة'), ('LOGIN', 'تسجيل دخول'), ('LOGIN_FAILED', 'محاولة دخول فاشلة'), ('LOGOUT', 'تسجيل خروج'), ('IMPORT', 'استيراد بيانات')], db_index=True, max_length=20, verbose_name='العملية')),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='نوع السجل')),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='رقم السجل')),
                ('entity_repr', models.CharField(blank=True, max_length=300, verbose_name='وصف السجل')),
                ('before_data', models.JSONField(blank=True, null=True, verbose_name='البيانات قبل')),
                ('after_data', models.JSONField(blank=True, null=True, verbose_name='البيانات بعد')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
