# Generated by Django 6.0.8 on 2026-09-30 13:54

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),  # pg_trgm powers fast partial (LIKE '%...%') search
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('search_text', models.TextField(default='', editable=False)),
                ('place_name', models.CharField(max_length=255, verbose_name='اسم المكان / التقاطع')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='الوصف / الموقع')),
                ('building_number', models.CharField(blank=True, max_length=20, verbose_name='رقم المبنى')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الشارع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'موقع',
                'verbose_name_plural': 'المواقع',
                'ordering': ['place_name', 'id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='location_search_trgm', opclasses=['gin_trgm_ops']), models.Index(fields=['place_name'], name='location_place_name_idx'), models.Index(fields=['building_number'], name='location_building_idx'), models.Index(fields=['street_number'], name='location_street_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreetName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('search_text', models.TextField(default='', editable=False)),
                ('common_name', models.CharField(max_length=255, verbose_name='الاسم الشائع للشارع')),
                ('official_name', models.CharField(max_length=255, verbose_name='الاسم الرسمي للشارع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
            ],
            options={
                'verbose_name': 'اسم شارع',
                'verbose_name_plural': 'أسماء الشوارع',
                'ordering': ['common_name', 'id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='street_search_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
