# Generated by Django 6.0.8 on 2026-10-08 12:47

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models




class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),  # creates the pg_trgm extension used by the search index
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('search_text', models.TextField(default='', editable=False)),
                ('kind', models.CharField(choices=[('complaint', 'شكوى'), ('inquiry', 'استفسار')], default='complaint', max_length=10, verbose_name='نوع الطلب')),
                ('national_id', models.CharField(blank=True, max_length=9, verbose_name='رقم الهوية')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='رقم الجوال')),
                ('point', models.CharField(blank=True, max_length=150, verbose_name='النقطة')),
                ('building_number', models.CharField(blank=True, max_length=20, verbose_name='رقم المبنى')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الشارع')),
                ('category', models.CharField(blank=True, max_length=150, verbose_name='نوع الشكوى')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الرفع'), ('uploaded', 'تم الرفع')], db_index=True, default='pending', max_length=10, verbose_name='الحالة')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرفع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='حُذف بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='عُدّل بواسطة')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='رُفعت بواسطة')),
            ],
            options={
                'verbose_name': 'شكوى مؤقتة',
                'verbose_name_plural': 'الشكاوى المؤقتة',
                'ordering': ['-created_at', '-id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='complaint_search_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
